/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package convertidor;

/**
 *
 * @author migue
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }
    
    private double convertir(double valor, String origen, String destino) {
        return (valor * obtenerFactor(origen)) / obtenerFactor(destino);
    }

private double obtenerFactor(String unidad) {
    switch (unidad) {
        case "Byte": return 1.0;
        case "Kilobyte": return Math.pow(1024, 1);
        case "Megabyte": return Math.pow(1024, 2);
        case "Gigabyte": return Math.pow(1024, 3);
        case "Terabyte": return Math.pow(1024, 4);
        case "Petabyte": return Math.pow(1024, 5);
        case "Zetabyte": return Math.pow(1024, 6);
        case "Yottabyte": return Math.pow(1024, 7);
        case "Brontobyte": return Math.pow(1024, 8);
        case "Geobyte": return Math.pow(1024, 9);
        default: return 1.0;
    }
}


private void convertirYMostrar() {
    String texto = cajaCantidad.getText().trim();

    if (texto.isEmpty()) {
        resultado.setText("Ingrese un número");
        return;
    }

    try {
        double valor = Double.parseDouble(texto);
        String unidadOrigen = (String) origenUnidad.getSelectedItem();
        String unidadDestino = (String) destinoUnidad.getSelectedItem();

        double resultadoValor = convertir(valor, unidadOrigen, unidadDestino);

        java.text.DecimalFormat df = new java.text.DecimalFormat("#,##0.##########");
        resultado.setText(df.format(resultadoValor) + " " + unidadDestino);

    } catch (NumberFormatException e) {
        resultado.setText("Solo se permiten números");
    }
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eTitulo = new javax.swing.JLabel();
        eSeleccionarMateria = new javax.swing.JLabel();
        destinoUnidad = new javax.swing.JComboBox<>();
        eCantidadConvertir = new javax.swing.JLabel();
        eResultado = new javax.swing.JLabel();
        origenUnidad = new javax.swing.JComboBox<>();
        cajaCantidad = new javax.swing.JTextField();
        eOrigen = new javax.swing.JLabel();
        eDestino = new javax.swing.JLabel();
        resultado = new javax.swing.JLabel();
        botonConvertir = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        eTitulo.setText("Convertidor de Unidades de Almacenamiento");

        eSeleccionarMateria.setText("Seleccione las unidades a Convertir");

        destinoUnidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Byte", "Kilobyte", "Megabyte", "Gigabyte", "Terabyte", "Petabyte", "Zetabyte", "Yottabyte", "Brontobyte", "Geobyte" }));
        destinoUnidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinoUnidadActionPerformed(evt);
            }
        });

        eCantidadConvertir.setText("Ingrese la cantidad a convertir");

        eResultado.setText("Resultado de la conversión");

        origenUnidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Byte", "Kilobyte", "Megabyte", "Gigabyte", "Terabyte", "Petabyte", "Zetabyte", "Yottabyte", "Brontobyte", "Geobyte" }));
        origenUnidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                origenUnidadActionPerformed(evt);
            }
        });

        cajaCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaCantidadActionPerformed(evt);
            }
        });
        cajaCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cajaCantidadKeyTyped(evt);
            }
        });

        eOrigen.setText("De (origen):");

        eDestino.setText("A (destino):");

        botonConvertir.setText("Convertir");
        botonConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConvertirActionPerformed(evt);
            }
        });

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(eTitulo))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(eSeleccionarMateria)
                            .addGap(166, 166, 166))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(eResultado)
                                .addComponent(eCantidadConvertir))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cajaCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                .addComponent(resultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(eOrigen)
                            .addComponent(eDestino))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(destinoUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(origenUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botonConvertir)
                        .addGap(152, 152, 152))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botonSalir)
                        .addGap(156, 156, 156))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(eTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(eSeleccionarMateria)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eOrigen)
                    .addComponent(origenUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destinoUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eDestino))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eCantidadConvertir)
                    .addComponent(cajaCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(botonConvertir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(resultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonSalir)
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void destinoUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinoUnidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destinoUnidadActionPerformed

    private void origenUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_origenUnidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_origenUnidadActionPerformed

    private void cajaCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaCantidadActionPerformed
        convertirYMostrar();
        
    }//GEN-LAST:event_cajaCantidadActionPerformed

    private void botonConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConvertirActionPerformed
        convertirYMostrar();

    }//GEN-LAST:event_botonConvertirActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        dispose();
        System.exit(0);
    }//GEN-LAST:event_botonSalirActionPerformed

    private void cajaCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaCantidadKeyTyped
        char c = evt.getKeyChar();

        // Permitir solo números, punto decimal y retroceso
        if (!Character.isDigit(c) && c != '.' && c != '\b') {
            evt.consume(); // no deja escribir el carácter
        }
    }//GEN-LAST:event_cajaCantidadKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonConvertir;
    private javax.swing.JButton botonSalir;
    private javax.swing.JTextField cajaCantidad;
    private javax.swing.JComboBox<String> destinoUnidad;
    private javax.swing.JLabel eCantidadConvertir;
    private javax.swing.JLabel eDestino;
    private javax.swing.JLabel eOrigen;
    private javax.swing.JLabel eResultado;
    private javax.swing.JLabel eSeleccionarMateria;
    private javax.swing.JLabel eTitulo;
    private javax.swing.JComboBox<String> origenUnidad;
    private javax.swing.JLabel resultado;
    // End of variables declaration//GEN-END:variables
}
